# Generated by Django 5.2 on 2025-05-06 15:14

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='icon')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20, verbose_name='rarity')),
                ('created_at', models.DateTimeField(default=timezone.now, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
                'indexes': [models.Index(fields=['name'], name='rpg_badge_name_856752_idx'), models.Index(fields=['rarity'], name='rpg_badge_rarity_217112_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='unlocked at')),
                ('progress', models.IntegerField(default=0, verbose_name='progress')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.achievement')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'achievement')},
                'indexes': [models.Index(fields=['user_profile', 'achievement'], name='rpg_userach_user_pr_47959b_idx'), models.Index(fields=['is_completed'], name='rpg_userach_is_comp_89b513_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='awarded at')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.badge')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'badge')},
                'indexes': [models.Index(fields=['user_profile', 'badge'], name='rpg_userbad_user_pr_102f1c_idx')],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(related_name='users', through='rpg.UserBadge', to='rpg.badge'),
        ),
    ]
