# Generated by Django 5.2 on 2025-05-07 11:23

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_auto_20250506_1914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'achievement', 'verbose_name_plural': 'achievements'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='is hidden'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='last activity'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='xp_reward',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='XP reward'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='XP'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['name'], name='rpg_achieve_name_02a758_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['xp_reward'], name='rpg_achieve_xp_rewa_64a7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['xp'], name='rpg_userpro_xp_17efa6_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['level'], name='rpg_userpro_level_3417a1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['last_activity'], name='rpg_userpro_last_ac_b7b75b_idx'),
        ),
    ]
