# Generated by Django 5.2.1 on 2025-05-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_alter_achievement_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='achievements',
        ),
    ]
