# Generated by Django 5.2.1 on 2025-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_remove_userprofile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.ManyToManyField(related_name='users', through='rpg.UserAchievement', to='rpg.achievement'),
        ),
    ]
