# Generated by Django 5.2 on 2025-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='portfolio_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
